---
- name: Restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
  when:
    - service_default_state | default('started') == 'started'
    - not ansible_check_mode
    - (ansible_facts['os_family'] == 'Debian') or (ansible_facts['os_family'] == 'RedHat')
